name: Build and Package Rust Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # 添加手动触发功能

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable]

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: ${{ matrix.rust }}

      - name: Install dependencies (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          sudo apt-get update || true
          sudo apt-get install -y libssl-dev pkg-config || true

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install openssl-light || true

      - name: Build the project
        run: cargo build --release

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rust-build-${{ matrix.os }}
          path: target/release/
