name: Build and Package Rust Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # 手动触发

jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-24.04

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies (Linux)
        run: |
          sudo apt-get update || true
          sudo apt-get install -y libssl-dev pkg-config || true
          
      - name: Build the project
        run: cargo build --release

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rust-build-linux
          path: target/release/

  build-windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies (Windows)
        run: |
          choco install openssl-light || true

      - name: Build the project
        run: cargo build --release

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rust-build-windows
          path: target/release/

  build-macos:
    name: Build on macOS
    runs-on: macos-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build the project
        run: cargo build --release

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rust-build-macos
          path: target/release/
